name: CI Workflow for Build
on:
 push:
jobs:
 courseendproject:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3
   - name: Setup JDK 11
     uses: actions/setup-java@v3
     with:
      java-version: '11'
      distribution: 'temurin'
      cache: maven
  - name: Buikd with maven
    run: mvn -B package --file pom.xml
     
